### ISSUE TITLE
Disable seconds in Binary

### ISSUE THREAD

**Issue by avbk** [amoledwatchfaces/amoledwatchfaces#1]
Hey guys,

first of all thanks for the cool watchfaces you designed! I'm using the Binary watch face occasionally and after a while I got used to the unfamiliar display of the numbers. But up to this day I stumble about the display changing from 4 to 6 digits and I honestly don't need the display of seconds at all. I saw in the play store that someone already asked about disabling the seconds via a setting, but I didn't notice any progress on this. 

Are you gonna ship this feature soon? And if not, do you need any help with that? Since I'm working in the industry for a couple of years, I'm quite familiar with Android and a bit with WearOS and could add the feature in some spare time...

**Comment by amoledwatchfaces** [comment]
Hi. I'll start working on it next week :) Will update you once its finished.

**Comment by amoledwatchfaces** [comment]
Added an option to disable seconds in v1.1.5 ;)

**Comment by avbk** [comment]
Awesome, just checked the settings and it work's like charm! Thanks a lot!
